### ISSUE TITLE
Inline tag Arrangement

### ISSUE THREAD

**Issue by sirakoff** [GetmeUK/HTMLString#1]
Is it possible to specify the order of tags  eg. a > strong > em . ??

**Comment by anthonyjb** [comment]
Hi @sirakoff - tag order is preserved when parsing and applying tags (e.g using format). So you can specify the order of tags by:

```
// Specify the order in the HTML itself
var s = new HTMLString.String( '<a><strong><em>Test</em></strong></a>');
```

... or by the order in which you format ...

```
// Specify the order using format
var s = new HTMLString.String('test');
s = s.format(0, 3, new HTMLString.Tag('a'));
s = s.format(0, 3, new HTMLString.Tag('strong'));
s = s.format(0, 3, new HTMLString.Tag('em'));
```

If you want to change the order of tags already applied the easiest approach would probably be to use `unformat` to clear the format from the string and then reapply the tags in the order you want, for example to achieve `em > strong > a` we could do:

```
// Specify a new order for the tags
s.unformat(0, 3);
s = s.format(0, 3, new HTMLString.Tag('em'));
s = s.format(0, 3, new HTMLString.Tag('strong'));
s = s.format(0, 3, new HTMLString.Tag('a'));
```
