### ISSUE TITLE
Removing attribute don't update head property of Tag

### ISSUE THREAD

**Issue by ba1uev** [GetmeUK/HTMLString#4]
Hello!
In `head()` method you cache the head part of the tag.
But when I try to remove attibute via `removeAttr()` method it don't update `_head` property
May be it  necessary to reset `_head` property to `null` at the end of `removeAttr()` method?

**Comment by anthonyjb** [comment]
Hi @ba1uev thanks for the report - this is indeed an issue as you describe, will patch shortly :+1:

**Comment by anthonyjb** [comment]
@ba1uev this has now been fixed and a new release pushed ([1.0.6](https://github.com/GetmeUK/HTMLString/releases/tag/1.0.6))
