### ISSUE TITLE
Blank element produces an error

### ISSUE THREAD

**Issue by bfintal** [GetmeUK/HTMLString#6]
(new HTMLString.String('<p></p>')).html()

Results in:

    Uncaught Error: Error at char 10 >> TypeError: Cannot read property '_tags' of undefined

However, using `span` doesn't produce any error:

    (new HTMLString.String('<span></span>')).html()

Results in an empty string and no error:

    ""

**Comment by anthonyjb** [comment]
Hi @bfintal,

This is I believe the expected result, HTMLString doesn't support parsing of empty strings, this is a design feature. If you read the opening to here: http://getcontenttools.com/api/html-string you should get an idea of how HTMLString works and why `'<p></p>'` wouldn't be handled.

HTMLString is designed to make handing HTML strings similar to handling text - but this has a number of limitations.

**Comment by bfintal** [comment]
Yup, but I think it would be better to return an empty string instead of throwing an error though!

Weird that it doesn't error out if I use `span` or `strong`, it only errors out for some elements like `div` or `p`. (let me update the OT with this)

**Comment by anthonyjb** [comment]
OK I'm not getting this result, if I do:

```
s = new window.HTMLString.String('<p></p>');
s.html()
```

I get an empty string as expected - perhaps browser specific?

**Comment by bfintal** [comment]
Nevermind, found the problem. I'm trying to get HTMLString to somehow support multiple lines and the error came from there.
